export const GET_INVOICES = 'GET_ALL_INVOICES';
export const GET_INVOICE_COUNT = 'GET_INVOICE_COUNT';
export const GET_CURRENT_INVOICE = 'GET_CURRENT_INVOICE';
export const CREATE_INVOICE = 'CREATE_INVOICE';
export const UPDATE_INVOICE = 'UPDATE_INVOICE';
export const DELETE_INVOICE = 'DELETE_INVOICE';
export const ACTION_FAILURE = 'ACTION_FAILURE';
